# https://github.com/sprintcube/docker-compose-lamp

version: "3"

services:
  webserver:
    build: 
      context: .docker/bin/webserver
    container_name: 'SERVER-7.2.x-webserver'
    restart: 'always'
    ports:
      - "8877:80"
      - "443:443"
    links: 
      - mysql
    volumes: 
      - ${DOCUMENT_ROOT-./www}:/var/www/html
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
    environment:
      - AMBIENTE:DEV

  mysql:
    build: .docker/bin/mysql
    container_name: 'SERVER-5.6-mysql'
    restart: 'always'
    ports:
      - "3377:3306"
    volumes: 
      - ./data/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
      - .docker/bin/mysql/extra.cnf:/etc/mysql/conf.d/extra.cnf
    environment:
        MYSQL_ROOT_PASSWORD: password
        DB_HOST: SERVER-5.6-mysql
        DB_PORT: 3306
        DB_DATABASE: SERVER
        DB_USERNAME: root
        DB_PASSWORD: password
        DOCKER_WEB_PORT: 8877

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'SERVER-phpmyadmin'
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - '8099:80'
    volumes: 
      - /sessions
